name: Check Code Style

on: [push, pull_request]

jobs:
  sort_format_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install isort black flake8 yamllint

      - name: Run isort
        run: |
          find . -name "*.py" -print0 | xargs -0 isort --line-length=180 --profile=black

      - name: Run black
        run: |
          find . -name "*.py" -print0 | xargs -0 black --line-length=180

      - name: Run flake8
        run: |
          find . -name "*.py" -print0 | xargs -0 flake8 --ignore=E265,E266,E501,E731,F401,W503,W504

      - name: Run yamllint
        run: |
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) -print0 \
          | xargs -0 yamllint -d "{extends: relaxed, rules: {line-length: {max: 180}}}"
